### ISSUE TITLE
Admin Interface to Close Elections & Stop Accepting Votes

### ISSUE THREAD

**Issue by arianabuilds** [siv-org/siv#31]
- feature requested by customers -

**Comment by dsernst** [comment]
Ok, this is now implemented.

### Admin toggle

- Commit: https://github.com/siv-org/siv/commit/1ef783a2990dfe6679a80fe654a1a9b3b79f8841
- Screenshot:
<img width="439" alt="image" src="https://github.com/user-attachments/assets/768248de-0307-4d43-abb8-096f193e2246">


### Message on vote page: 

- Commit: https://github.com/siv-org/siv/commit/05f02b5847a696fd9088a23457a949f122cf0418
- Screenshot:
![image](https://github.com/user-attachments/assets/2551d0fb-bb5c-4281-bb5a-6ee236057689)

### Other implementation details.

1. Because this hooks into the `/check-auth-token` route, if they try to ignore the message and submit a vote anyway, [the encrypted vote will get stored in the `votes-rejected` collection](https://github.com/siv-org/siv/blob/05f02b5847a696fd9088a23457a949f122cf0418/pages/api/submit-vote.ts#L60), along with the timestamp and rejection message. 
2. The vote will not get added to the public list of votes, nor will the voter's name become checked in the admin UI. 
3. It will trigger a pushover notification about it to Server Admin.
4. It will not be visible for `auth=preview` or `auth=link`, which both skip this auth token check. Might want to fix that for `auth=link` in the future, but not urgent.
5. It does not currently display the time when the election was closed. Unclear how necessary that is.
